image:
  repository: zwavejs/zwave-js-ui
  tag: 11.10.1
  pullPolicy: IfNotPresent

env:
  - name: ZWAVE_JS_EXTERNAL_CONFIG
    value: /usr/src/app/store/.config-db
  - name: ZWAVEJS_SERIAL_PORT
    value: /dev/serial/by-id/usb-Nabu_Casa_ZWA-2_80B54EE15D30-if00

securityContext:
  runAsUser: 0
  allowPrivilegeEscalation: true
  capabilities:
    add:
      - SYS_RAWIO
      - SYS_ADMIN

persistence:
  enabled: true
  existingClaim: zwave-js-ui-data
  mountPath: /usr/src/app/store

usbDevice: /dev/serial/by-id/usb-Nabu_Casa_ZWA-2_80B54EE15D30-if00

resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 192Mi

deployment:
  annotations:
    checksum/values: "{{ .Values | toJson | sha256sum }}"
