image:
  repository: ghcr.io/blakeblackshear/frigate
  tag: 0.16.3
  pullPolicy: IfNotPresent

env:
  TZ: America/Los_Angeles

persistence:
  config:
    enabled: true
    type: pvc
    existingClaim: frigate-config
    mountPath: /config
  data:
    enabled: true
    type: pvc
    existingClaim: frigate-data
  media:
    enabled: true
    type: hostPath
    hostPath: /srv/media/video/cameras
  cache:
    enabled: true
    type: emptyDir
    medium: Memory
    sizeLimit: 1Gi
    mountPath: /dev/shm
  dri:
    enabled: true
    type: hostPath
    hostPath: /dev/dri
    mountPath: /dev/dri

service:
  main:
    ports:
      http:
        enabled: true
        primary: true
        type: ClusterIP
        clusterIP: ""
        port: 5000
      rtmp:
        enabled: false

securityContext:
  privileged: true

resources:
  requests:
    cpu: 2000m
    memory: 2Gi
  limits:
    cpu: 4000m
    memory: 6Gi

configmap:
  config:
    enabled: false

deployment:
  annotations:
    checksum/values: "{{ .Values | toJson | sha256sum }}"
