apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - jellyfin
  - gitea
  - frigate
  - mosquitto
  - zwave-js-ui
  - hass
  - music-assistant
  - omada
  # The following are non-helm, so we only need to add the Application manifest here.
  - samba/application.yaml
