apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://dl.gitea.com/charts/
    chart: gitea
    targetRevision: 10.4.1
    helm:
      values: |
        gitea:
          config:
            database:
              DB_TYPE: sqlite3
              PATH: /data/gitea/gitea.db
            server:
              DOMAIN: gitea.agate.home
              ROOT_URL: http://gitea.agate.home/
              SSH_DOMAIN: gitea.agate.home
              SSH_PORT: 22
              SSH_LISTEN_PORT: 22
          env:
            - name: USER_UID
              value: "2000"
            - name: USER_GID
              value: "2000"
          
          extraVolumes:
            - name: gitea-shared-storage
              hostPath:
                path: /srv/apps/gitea/data
                type: DirectoryOrCreate
        
          extraVolumeMounts:
            - name: gitea-shared-storage
              mountPath: /data
      
        persistence:
          enabled: false
          #storageClass: ""
          #accessMode: ReadWriteOnce
          #size: 10Gi
          #type: hostPath
          #hostPath:
          #  path: /srv/apps/gitea/data
          #  type: Directory
   
        podSecurityContext:
          fsGroup: 2000
        
        securityContext:
          runAsUser: 2000
          runAsGroup: 2000

        containerSecurityContext:
          runAsUser: 2000
          runAsGroup: 2000
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
            add: ["SYS_CHROOT"]

        service:
          http:
            type: ClusterIP
            clusterIP: ""
            port: 3000
        
          ssh:
            type: NodePort
            clusterIP: ""
            nodePort: 32222
        
        global:
          postgresql:
            enabled: false
          
        postgresql:
          enabled: false
    
        postgresql-ha:
          enabled: false
    
        redis:
          enabled: false
    
        redis-cluster:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: services

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
