apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://dl.gitea.com/charts/
    chart: gitea
    targetRevision: 10.4.1
    helm:
      values: |
        gitea:
        config:
          database:
            DB_TYPE: sqlite3
            PATH: /data/gitea/gitea.db
          server:
            DOMAIN: gitea.agate.lan
            ROOT_URL: http://gitea.agate.lan/
            SSH_DOMAIN: gitea.agate.lan
            SSH_PORT: 22
            SSH_LISTEN_PORT: 22

      persistence:
        enabled: true
        storageClass: local-path
        size: 10Gi

      service:
        http:
          type: ClusterIP
          port: 3000
        ssh:
          type: LoadBalancer
          port: 22

      postgresql:
        enabled: false

      postgresql-ha:
        enabled: false

      redis:
        enabled: false

      redis-cluster:
        enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: services

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
