apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://jellyfin.github.io/jellyfin-helm
    targetRevision: 2.7.0
    chart: jellyfin
    helm:
      values: |
        image:
          repository: jellyfin/jellyfin
          tag: latest

        service:
          type: ClusterIP
          port: 8096

        persistence:
          config:
            enabled: true
            type: hostPath
            hostPath: /srv/apps/jellyfin/config
            readOnly: false
          cache:
            enabled: true
            type: hostPath
            hostPath: /srv/apps/jellyfin/cache
            readOnly: false
          media:
            enabled: true
            type: hostPath
            hostPath: /srv/media
            readOnly: true
        
        podSecurityContext:
          fsGroup: 2000

        securityContext:
          runAsUser: 2000
          runAsGroup: 2000

        resources:
          requests:
            cpu: "500m"
            memory: "2Gi"
          limits:
            cpu: "2500m"
            memory: "10Gi"

  destination:
    server: https://kubernetes.default.svc
    namespace: services

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
