apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hass
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: http://pajikos.github.io/home-assistant-helm-chart/
      chart: home-assistant
      targetRevision: 0.3.41
      helm:
        valueFiles:
          - $values/services/hass/values.yaml

    - repoURL: https://github.com/msaavedra/zircon.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: services

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
