apiVersion: v1
kind: PersistentVolume
metadata:
  name: hass-data
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /srv/apps/hass/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hass-data
  namespace: services
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: hass-data
  resources:
    requests:
      storage: 50Gi