apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mosquitto
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://storage.googleapis.com/t3n-helm-charts
      chart: mosquitto
      targetRevision: 2.4.1
      helm:
        valueFiles:
          - $values/services/mosquitto/values.yaml

    - repoURL: https://github.com/msaavedra/zircon.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: services

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
