apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: services
spec:
  selector:
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/name: mosquitto
  type: NodePort
  ports:
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: mqtt
      nodePort: 31883
