image:
  repository: eclipse-mosquitto
  tag: 2.0.15
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 1883

mosquitto:
  persistence:
    enabled: true
    existingClaim: mosquitto-data
    size: 2Gi

  config: |
    allow_anonymous true
