image:
  repository: eclipse-mosquitto
  tag: 1.6.12
  pullPolicy: IfNotPresent

ports:
  mqtt:
    port: 1883
    nodePort: 31883
    protocol: TCP
  websocket:
    port: 9001
    nodePort: 39090
    protocol: TCP

podSecurityContext:
  runAsUser: 0
  fsGroup: 0

securityContext:
  runAsUser: 0
  fsGroup: 0

persistence:
  enabled: true
  existingClaim: mosquitto-data
  size: 2Gi

config: |
  persistence true
  persistence_location /mosquitto/data/
  log_dest stdout
  listener 1883
  allow_anonymous true

acls: |
  topic readwrite #
