apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: samba
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/msaavedra/zircon.git
    targetRevision: main
    path: services/samba

  destination:
    server: https://kubernetes.default.svc
    namespace: samba

  syncPolicy:
    automated:
      prune: true
      selfHeal: true