apiVersion: apps/v1
kind: Deployment
metadata:
  name: samba
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samba
  template:
    metadata:
      labels:
        app: samba
    spec:
      containers:
        - name: samba
          image: ghcr.io/servercontainers/samba:latest
          env:
            - name: AVAHI_DISABLE
              value: "true"
            - name: GROUP_smbadmins
              value: "1000"
            - name: USER_mike
              valueFrom:
                secretKeyRef:
                  name: samba-users
                  key: samba_pw_mike
            - name: GROUPS_mike
              value: smbadmins

          securityContext:
            runAsUser: 0

          ports:
            - containerPort: 445
              name: smb

          volumeMounts:
            - name: config
              mountPath: /container/config/samba
              readOnly: true

            - name: state
              mountPath: /var/lib/samba

            - name: share-data
              mountPath: /shares

      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: samba-config

        - name: state
          persistentVolumeClaim:
            claimName: samba-state

        - name: share-data
          hostPath:
            path: /srv/smb
            type: DirectoryOrCreate