apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Note that application.yaml is excluded here, it belongs to argocd.
  - deployment.yaml
  - service.yaml
  - storage.yaml
