apiVersion: v1
kind: Service
metadata:
  name: samba
  namespace: services
spec:
  type: LoadBalancer

  loadBalancerIP: 10.235.2.5

  ports:
    - name: smb
      port: 445
      targetPort: 445
      protocol: TCP

  selector:
    app: samba
