apiVersion: v1
kind: PersistentVolume
metadata:
  name: samba-config
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /srv/apps/samba/config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: samba-config
  namespace: services
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: samba-config
  resources:
    requests:
      storage: 5Gi
