apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-storage
  namespace: argocd
spec:
  project: default

  source:
    repoURL: oci://ghcr.io/rancher
    targetRevision: 0.0.30
    chart: local-path-provisioner
    helm:
      values: |
        storageClass:
          create: true
          defaultClass: true
          name: local-path
        nodePathMap:
          - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
            paths:
              - /srv/k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: local-path-storage

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
