apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: omada
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: oci://registry-1.docker.io/mbentley/omada-controller-helm
      chart: omada-controller
      targetRevision: 1.0.2
      helm:
        valueFiles:
          - $values/services/omada/values.yaml

    - repoURL: https://github.com/msaavedra/zircon.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: services

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
