apiVersion: v1
kind: Service
metadata:
  name: omada
spec:
  type: LoadBalancer
  loadBalancerIP: 10.235.2.7   # change this to old omada address once we get this running smoothly.
  ports:
    - name: https
      port: 8043
    - name: inform
      port: 8088
    - name: discovery
      port: 29810
    - name: adoption
      port: 29811
    - name: upgrade
      port: 29812
    - name: manager
      port: 29813
  selector:
    app: omada
