apiVersion: v1
kind: PersistentVolume
metadata:
  name: omada-data
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /srv/apps/omada/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omada-data
  namespace: services
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: omada-data
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: omada-logs
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /srv/apps/omada/logs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omada-logs
  namespace: services
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: omada-logs
  resources:
    requests:
      storage: 2Gi
